# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='group',
            new_name='id_server_group',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='port',
            new_name='sshport',
        ),
    ]
