# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'id'),
        ),
    ]
