# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0002_auto_20161024_0319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='dss_command',
        ),
        migrations.RenameModel(
            old_name='Server',
            new_name='dss_server',
        ),
        migrations.RenameModel(
            old_name='Server_group',
            new_name='dss_server_group',
        ),
        migrations.RenameModel(
            old_name='Server_history',
            new_name='dss_server_history',
        ),
    ]
