# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_auto_20160808_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_groups',
            name='description',
            field=models.CharField(max_length=200, verbose_name=b'description'),
        ),
    ]
