# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_auto_20161227_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dss_command',
            options={'verbose_name': ' Command', 'verbose_name_plural': ' Commands'},
        ),
        migrations.AlterModelOptions(
            name='dss_server',
            options={'verbose_name': ' Server', 'verbose_name_plural': ' Servers'},
        ),
        migrations.AlterModelOptions(
            name='dss_server_group',
            options={'verbose_name': 'Server Group', 'verbose_name_plural': 'Servers Groups'},
        ),
        migrations.AlterModelOptions(
            name='dss_server_history',
            options={'verbose_name': ' Server History', 'verbose_name_plural': ' Servers History'},
        ),
        migrations.AddField(
            model_name='dss_server',
            name='os',
            field=models.CharField(choices=[(b'0', 'Linux Ubuntu'), (b'1', 'Linux Centos'), (b'2', 'Linux Fedora'), (b'3', 'Linux Mandriba')], default=b'1', max_length=1),
        ),
    ]
