# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0004_auto_20161227_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='dss_server_os',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('name', models.CharField(choices=[(b'0', 'Linux Ubuntu'), (b'1', 'Linux Centos'), (b'2', 'Linux Fedora'), (b'3', 'Linux Mandriba')], default=b'0', max_length=1)),
                ('version', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[(b'0', 'Inactive'), (b'1', 'Active')], default=b'1', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'updated')),
            ],
        ),
        migrations.RenameField(
            model_name='dss_server',
            old_name='root',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dss_server',
            name='os',
        ),
        migrations.AddField(
            model_name='dss_server',
            name='cpu',
            field=models.CharField(default=-1, max_length=200, verbose_name=b'cpu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dss_server',
            name='dd_capacity',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4, verbose_name=b'disc capacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dss_server',
            name='ram',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=3, verbose_name=b'memory ram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dss_server',
            name='status',
            field=models.CharField(choices=[(b'0', 'Inactive'), (b'1', 'Active')], default=b'1', max_length=1, verbose_name=b'status'),
        ),
        migrations.AddField(
            model_name='dss_server',
            name='id_server_os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dss.dss_server_os'),
            preserve_default=False,
        ),
    ]
