# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0004_auto_20160808_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default='Server', max_length=200, verbose_name=b'password'),
            preserve_default=False,
        ),
    ]
