# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0005_server_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('description', models.CharField(max_length=200, verbose_name=b'description')),
                ('command', models.CharField(max_length=200, verbose_name=b'command')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name=b'added')),
                ('status', models.CharField(choices=[(b'0', 'Incomplete'), (b'1', 'Complete')], default=b'u', max_length=1, verbose_name=b'status')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.Server')),
            ],
        ),
    ]
