# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0006_server_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server_groups',
            new_name='Server_group',
        ),
    ]
