# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0006_auto_20161227_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dss_server',
            name='id_server_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomaterial', to='dss.dss_server_os'),
        ),
    ]
