# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0007_auto_20160809_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='group',
            field=models.CharField(choices=[(b'mysql', 'mysql'), (b'apache', 'apache')], default=b'u', max_length=1, verbose_name=b'status'),
        ),
    ]
