# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0007_auto_20161227_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dss_server',
            name='id_server_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dss_server_os'),
        ),
        migrations.AlterField(
            model_name='dss_server_os',
            name='name',
            field=models.CharField(choices=[(b'Linux Ubuntu', 'Linux Ubuntu'), (b'Linux Centos', 'Linux Centos'), (b'Linux Fedora', 'Linux Fedora'), (b'Linux Mandriba', 'Linux Mandriba')], default=b'0', max_length=1),
        ),
    ]
