# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0008_command_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='server',
            field=models.ForeignKey(default='Command', on_delete=django.db.models.deletion.CASCADE, to='dss.Server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='group',
            field=models.CharField(choices=[(b'0', 'mysql'), (b'1', 'files'), (b'2', 'history'), (b'3', 'others')], default=b'u', max_length=1, verbose_name=b'status'),
        ),
    ]
