# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0008_auto_20161227_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dss_server_os',
            name='name',
            field=models.CharField(choices=[(b'Linux Ubuntu', 'Linux Ubuntu'), (b'Linux Centos', 'Linux Centos'), (b'Linux Fedora', 'Linux Fedora'), (b'Linux Mandriba', 'Linux Mandriba')], max_length=200, verbose_name=b'name'),
        ),
    ]
