# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0010_remove_command_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='server',
            field=models.ForeignKey(default='Command', on_delete=django.db.models.deletion.CASCADE, to='dss.Server'),
            preserve_default=False,
        ),
    ]
