# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0010_dss_server_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dss_server_action',
            options={'verbose_name': 'Server action', 'verbose_name_plural': 'Servers actions'},
        ),
        migrations.AddField(
            model_name='dss_server_action',
            name='id_server',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dss.dss_server'),
            preserve_default=False,
        ),
    ]
