# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0011_auto_20161227_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dss_server',
            name='dd_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=b'disc capacity'),
        ),
    ]
