# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0013_auto_20161227_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='dss_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('name', models.CharField(max_length=200, verbose_name=b'name')),
                ('description', models.CharField(max_length=200, verbose_name=b'description')),
                ('version', models.DecimalField(decimal_places=2, max_digits=4)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name=b'added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'updated')),
                ('status', models.CharField(choices=[(b'0', 'Inactive'), (b'1', 'Active')], default=b'u', max_length=1, verbose_name=b'status')),
            ],
            options={
                'verbose_name': ' Service',
                'verbose_name_plural': ' Services',
            },
        ),
        migrations.AddField(
            model_name='dss_command',
            name='id_service',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dss.dss_service'),
            preserve_default=False,
        ),
    ]
