# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0014_auto_20161227_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dss_server',
            name='pyro_object_url',
            field=models.CharField(default=-1, max_length=200, verbose_name=b'object pyro'),
            preserve_default=False,
        ),
    ]
