# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('name', models.CharField(max_length=200, verbose_name=b'name')),
                ('url_api', models.CharField(max_length=200, verbose_name=b'url api')),
                ('token', models.CharField(max_length=200, verbose_name=b'token')),
            ],
            options={
                'verbose_name': 'Ionic Account',
                'verbose_name_plural': 'Ionic Accounts',
            },
        ),
        migrations.CreateModel(
            name='nofication_push',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('sentTo', models.CharField(max_length=200, verbose_name=b'send to')),
                ('message', models.CharField(max_length=200, verbose_name=b'message')),
                ('androidmessage', models.CharField(max_length=200, verbose_name=b'android message')),
                ('priority', models.CharField(choices=[(b'0', 'low'), (b'1', 'medium'), (b'2', 'high')], default=b'1', max_length=1, verbose_name=b'priority')),
                ('title', models.CharField(max_length=200, verbose_name=b'title')),
                ('id_account', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='ionic.account')),
            ],
            options={
                'verbose_name': 'Ionic Notification',
                'verbose_name_plural': 'Ionic Notifications',
            },
        ),
    ]
